### PR TITLE
Introduce Marshaling library

### PR DESCRIPTION
**Pull request by tstruk**
Add generic Marshaling library for TPM types

### CODE REVIEW

**Comment by flihp** [comment]
I think this build failure is unrelated. May have come from 0e72ba6a24413a8a438e5191c2fe97fd61055c83. If so then it's clang and FORTIFY_SOURCE having a bad interaction?

**Comment by tstruk** [comment]
No, it doesn't look like it is from 0e72ba6.

**Comment by flihp** [comment]
Fixed issue introduced by 0e72ba6a24413a8a438e5191c2fe97fd61055c83 #484. This should resolve the build failure. Will start the review tomorrow.

**Comment by tstruk** [comment]
New PR created

**Pull request closed without merging**
